swagger: "2.0"
info:
  title: Demo APIs
  version: "2.0"
  description: Use VSCode plugin [OpenAPI (Swagger) Editor](https://marketplace.visualstudio.com/items?itemName=42Crunch.vscode-openapi) to edit this document.
host: localhost:8080
schemes:
  - http
  - https

paths:
  /v1/device/online:
    get:
      summary: 在一定时间内均匀上线设备
      description: 仅仅上线设备，不进行数据上报
      tags:
        - pressure
      operationId: deviceOnline
      produces:
        - "application/json"
      parameters:
        - in: query
          name: deviceNumber
          type: integer
          description: 上线的设备数，也是压测的设备数
        - in: query
          name: deviceType
          type: string
          description: 压测的设备类型
        - in: query
          name: part
          type: integer
          description: 每批上线多少设备
        - in: query
          name: rest
          type: integer
          description: 两批设备上线间隔(ms)
      responses:
        200:
          description: success
          schema:
            $ref: "#/definitions/BaseResp"
        400:
          description: parameter error
        500:
          description: server error
  /v1/pressure/start:
    post:
      summary: 开始压测
      description: 在一定时间内均匀上线设备，然后在设置周期内尽量均匀的上报数据
      tags:
        - pressure
      operationId: pressureStart
      produces:
        - "application/json"
      parameters:
        - in: query
          name: deviceNumber
          type: integer
          description: 上线的设备数，也是压测的设备数
        - in: query
          name: deviceType
          type: string
          description: 压测的设备类型
        - in: query
          name: part
          type: integer
          description: 每批上线多少设备
        - in: query
          name: rest
          type: integer
          description: 两批设备上线间隔(ms)
        - in: query
          name: period
          type: integer
          description: 上报数据的周期(ms);设备将在此周期内尽量均匀上报数据,不能小于100
        - in: query
          name: topic
          type: string
          description: 上报数据类型，data、raw
        - in: body
          name: body
          required: true
          schema:
            $ref: "#/definitions/SandData"
      responses:
        200:
          description: success
          schema:
            $ref: "#/definitions/BaseResp"
        400:
          description: parameter error
        500:
          description: server error
  /v1/pressure/stop:
    get:
      summary: 停止压测
      description: 断开压测设备mqtt连接,停止定时任务
      tags:
        - pressure
      operationId: pressureStop
      produces:
        - "application/json"
      responses:
        200:
          description: success
          schema:
            $ref: "#/definitions/BaseResp"
        400:
          description: parameter error
        500:
          description: server error
# common parameters
parameters:
  queryPageSize:
    name: page_size
    in: query
    type: integer
    required: false
    default: 20
    description: 每页条数
  queryCurrentPage:
    name: current_page
    in: query
    type: integer
    required: false
    default: 1
    description: 当前页

# common data structure
definitions:
  BaseResp:
    type: object
    properties:
      message:
        type: string
  OnePageData:
    type: object
    properties:
      pagination:
        type: object
        properties:
          totalSize:
            type: integer
            example: 1000
          currentPage:
            type: integer
            example: 1
          pageSize:
            type: integer
            example: 20
  SandData:
    type: object
    properties:
      data:
        type: string
        description: 上报的数据，为base64字符串
